// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aibrsdzjvlejirlyfkzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpYnJzZHpqdmxlamlybHlma3pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDIwODksImV4cCI6MjA2MzU3ODA4OX0.5QP-KG0bzvooFmOjtmnmBGXjRKH-vorBAMLL-Y3B_eY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);